# Generated by Django 3.2 on 2022-01-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_student_email'),
        ('integrationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(verbose_name='board id')),
                ('project_command', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trello_board', to='automation.command', verbose_name='команда')),
                ('trello', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='integrationapp.trello', verbose_name='trello')),
            ],
        ),
    ]
