# Generated by Django 3.2 on 2022-01-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('integrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trello',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trello', to='automation.project', verbose_name='проект'),
        ),
    ]
