# Generated by Django 3.2 on 2022-01-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0002_trelloboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloboard',
            name='trello',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='integrationapp.trello', verbose_name='trello'),
        ),
    ]
