# Generated by Django 3.2 on 2022-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0003_alter_trelloboard_trello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloboard',
            name='board_id',
            field=models.CharField(max_length=50, verbose_name='board id'),
        ),
    ]
