# Generated by Django 3.2 on 2022-01-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0004_alter_trelloboard_board_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trelloboard',
            options={'verbose_name': 'Trello board', 'verbose_name_plural': 'Trello boards'},
        ),
    ]
