# Generated by Django 3.2 on 2022-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0006_rename_project_command_trelloboard_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trello',
            options={'verbose_name': 'Trello workspace', 'verbose_name_plural': 'Trello  workspaces'},
        ),
        migrations.AddField(
            model_name='trello',
            name='workspace_id',
            field=models.CharField(default='', max_length=50, verbose_name='board id'),
            preserve_default=False,
        ),
    ]
