# Generated by Django 3.2 on 2022-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0007_auto_20220123_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trello',
            name='workspace_id',
            field=models.CharField(max_length=50, verbose_name='workspace id'),
        ),
    ]
