# Generated by Django 3.2.9 on 2022-01-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('category', models.CharField(choices=[('beginner', 'Новичок'), ('beginner_plus', 'Новичок+'), ('junior', 'Джун')], max_length=255, verbose_name='Категория')),
                ('call_time', models.CharField(choices=[('time_18_19', 'От 18:00 до 20'), ('time_19_20', 'От 19:00 до 20')], max_length=255, verbose_name='Возможное время созвона')),
                ('possibly_call_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Точное время созвона')),
                ('telegram_user_name', models.CharField(max_length=255, verbose_name='Телеграм ник')),
                ('telegram_chat_id', models.CharField(max_length=255, verbose_name='Телеграм chat_id')),
                ('devman_user_name', models.CharField(max_length=255, verbose_name='Devman ник')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
