# Generated by Django 3.2 on 2022-01-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название команды')),
                ('meeting_time', models.CharField(blank=True, max_length=50, verbose_name='Время созвона')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('start_date', models.DateField(db_index=True, verbose_name='дата начала проекта')),
                ('end_date', models.DateField(db_index=True, verbose_name='дата окончания проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('start_at', models.CharField(blank=True, max_length=50, verbose_name='Созвон ОТ')),
                ('end_at', models.CharField(blank=True, max_length=50, verbose_name='Созвон ДО')),
            ],
            options={
                'verbose_name': 'ПМ',
                'verbose_name_plural': 'ПМы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('far_east', models.BooleanField(default=False, verbose_name='Дальний восток')),
                ('tg_username', models.CharField(max_length=255, verbose_name='Телеграм ник')),
                ('tg_chat_id', models.CharField(max_length=255, verbose_name='Телеграм chat_id')),
                ('discord_username', models.CharField(default='example#1234', max_length=255, verbose_name='Discort ник')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='automation.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='ParticipantProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.CharField(blank=True, max_length=50, verbose_name='Время созвона')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_project', to='automation.command', verbose_name='команда')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_project', to='automation.projectmanager', verbose_name='ПМ')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_project', to='automation.student', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='automation.project', verbose_name='проект'),
        ),
    ]
