# Generated by Django 3.2 on 2022-01-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20220118_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название команды'),
        ),
    ]
