# Generated by Django 3.2 on 2022-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20220121_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantproject',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время созвона'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='end_at',
            field=models.CharField(blank=True, max_length=50, verbose_name='Созвон ДО'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='start_at',
            field=models.CharField(blank=True, max_length=50, verbose_name='Созвон ОТ'),
        ),
    ]
