# Generated by Django 3.2 on 2022-01-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20220122_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время созвона'),
        ),
    ]
