# Generated by Django 3.2 on 2022-01-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_command_command_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('start_date', models.DateField(db_index=True, verbose_name='дата начала проекта')),
                ('end_date', models.DateField(db_index=True, verbose_name='дата окончания проекта')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='automation.project', verbose_name='проект'),
        ),
    ]
