# Generated by Django 3.2 on 2022-01-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20220119_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
