# Generated by Django 3.2 on 2022-01-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20220121_1750'),
        ('automation', '0005_remove_student_user'),
    ]

    operations = [
    ]
