# Generated by Django 3.2 on 2022-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_merge_20220123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название команды'),
        ),
    ]
